# Generated by Django 4.2 on 2023-05-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(default=False)),
                ('expenses', models.IntegerField()),
                ('income', models.IntegerField()),
                ('salary', models.FloatField()),
                ('spouse_salary', models.FloatField()),
                ('pasport', models.CharField(max_length=100)),
                ('snils', models.CharField(max_length=100)),
                ('inn', models.CharField(max_length=100)),
                ('loan_amount', models.FloatField()),
                ('loan_term', models.IntegerField()),
                ('interest_rate', models.FloatField()),
                ('monthly_payment', models.FloatField()),
                ('main_sum', models.FloatField()),
            ],
        ),
    ]
