# Generated by Django 4.2 on 2023-05-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('seniority', models.IntegerField()),
                ('home', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
                ('age', models.IntegerField()),
                ('marital', models.CharField(max_length=100)),
                ('records', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('expenses', models.IntegerField()),
                ('income', models.IntegerField()),
                ('assets', models.IntegerField()),
                ('debt', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('finrat', models.DecimalField(decimal_places=9, max_digits=12)),
                ('savings', models.DecimalField(decimal_places=9, max_digits=12)),
                ('pasport', models.IntegerField()),
                ('snils', models.IntegerField()),
                ('inn', models.IntegerField()),
            ],
        ),
    ]
